"""game_sessions: bankroll, apuesta base, limite de mesa y estrategia pasan a NOT NULL

Revision ID: 6d1cb2c2210c
Revises: d362196dee55
Create Date: 2026-09-08 16:30:45.245232
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d1cb2c2210c'
down_revision: Union[str, None] = 'd362196dee55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic no autodetecta cambios en CHECK constraints: al dejar de ser
    # nullable `strategy_selected`, la rama "IS NULL" del CHECK de §2.8 sobra.
    op.drop_constraint("ck_session_strategy_mode_matches_strategy", "game_sessions", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_sessions', 'bankroll_start',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('game_sessions', 'bankroll_current',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('game_sessions', 'base_bet',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('game_sessions', 'table_limit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('game_sessions', 'strategy_selected',
               existing_type=sa.VARCHAR(length=19),
               nullable=False)
    # ### end Alembic commands ###

    op.create_check_constraint("ck_session_strategy_mode_matches_strategy", "game_sessions", "(strategy_mode = 'two_sector') = (strategy_selected = 'two_sector_recovery')")


def downgrade() -> None:
    op.drop_constraint("ck_session_strategy_mode_matches_strategy", "game_sessions", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_sessions', 'strategy_selected',
               existing_type=sa.VARCHAR(length=19),
               nullable=True)
    op.alter_column('game_sessions', 'table_limit',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('game_sessions', 'base_bet',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('game_sessions', 'bankroll_current',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('game_sessions', 'bankroll_start',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    # ### end Alembic commands ###
    op.create_check_constraint("ck_session_strategy_mode_matches_strategy", "game_sessions", "strategy_selected IS NULL OR (strategy_mode = 'two_sector') = (strategy_selected = 'two_sector_recovery')")
