"""schema inicial completo (usuarios, juegos, sesiones, giros, apuestas, sugerencias, pantallazos)

Revision ID: d362196dee55
Revises: 
Create Date: 2026-09-08 16:16:04.654862
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd362196dee55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('access_type', sa.Enum('trial', 'invited', 'full', name='access_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('game_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('house_edge', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('categories_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'name', name='uq_game_variant_name')
    )
    op.create_index(op.f('ix_game_variants_game_id'), 'game_variants', ['game_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('payment_token_ref', sa.String(length=255), nullable=True),
    sa.Column('plan_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('game_variant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'closed', 'abandoned', name='session_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('window_size', sa.Integer(), nullable=False),
    sa.Column('bankroll_start', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bankroll_current', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('base_bet', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('table_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('strategy_selected', sa.Enum('flat', 'martingale', 'dalembert', 'fibonacci', 'two_sector_recovery', name='strategy_selected', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('strategy_stage', sa.Integer(), nullable=False),
    sa.Column('strategy_mode', sa.Enum('single', 'two_sector', name='strategy_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("strategy_selected IS NULL OR (strategy_mode = 'two_sector') = (strategy_selected = 'two_sector_recovery')", name='ck_session_strategy_mode_matches_strategy'),
    sa.ForeignKeyConstraint(['game_variant_id'], ['game_variants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_game_variant_id'), 'game_sessions', ['game_variant_id'], unique=False)
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_index(op.f('ix_payment_events_subscription_id'), 'payment_events', ['subscription_id'], unique=False)
    op.create_table('screenshot_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_hash', sa.String(length=128), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('classification_result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'rejected_not_relevant', 'needs_confirmation', 'ready_for_extraction', 'confirmed', 'discarded_by_user', 'failed', name='screenshot_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshot_uploads_image_hash'), 'screenshot_uploads', ['image_hash'], unique=False)
    op.create_index(op.f('ix_screenshot_uploads_session_id'), 'screenshot_uploads', ['session_id'], unique=False)
    op.create_index(op.f('ix_screenshot_uploads_user_id'), 'screenshot_uploads', ['user_id'], unique=False)
    op.create_table('session_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('total_suggestions', sa.Integer(), nullable=False),
    sa.Column('matched_suggestions', sa.Integer(), nullable=False),
    sa.Column('baseline_matched', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('spins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('spin_index', sa.Integer(), nullable=False),
    sa.Column('result_value', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Enum('manual', 'screenshot', name='spin_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('screenshot_upload_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['screenshot_upload_id'], ['screenshot_uploads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'spin_index', name='uq_spin_session_index')
    )
    op.create_index(op.f('ix_spins_session_id'), 'spins', ['session_id'], unique=False)
    op.create_table('bankroll_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('spin_id', sa.UUID(), nullable=True),
    sa.Column('strategy', sa.String(length=40), nullable=False),
    sa.Column('suggested_bet', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('risk_warning', sa.Text(), nullable=True),
    sa.Column('ruin_probability_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spin_id'], ['spins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankroll_suggestions_session_id'), 'bankroll_suggestions', ['session_id'], unique=False)
    op.create_index(op.f('ix_bankroll_suggestions_spin_id'), 'bankroll_suggestions', ['spin_id'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('spin_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('option_label', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('followed_suggestion', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'resolved', 'cancelled', name='bet_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('payout', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('net_change', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spin_id'], ['spins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_session_id'), 'bets', ['session_id'], unique=False)
    op.create_index(op.f('ix_bets_spin_id'), 'bets', ['spin_id'], unique=False)
    op.create_table('statistical_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('spin_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('option_label', sa.String(length=60), nullable=False),
    sa.Column('theoretical_probability', sa.Float(), nullable=False),
    sa.Column('observed_frequency_shrunk', sa.Float(), nullable=False),
    sa.Column('deviation', sa.Float(), nullable=False),
    sa.Column('significance_score', sa.Float(), nullable=False),
    sa.Column('strength', sa.Enum('strong', 'medium', 'weak', name='signal_strength', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('ev', sa.Float(), nullable=False),
    sa.Column('chi_square_pvalue', sa.Float(), nullable=True),
    sa.Column('window_size_used', sa.Integer(), nullable=False),
    sa.Column('is_top3', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spin_id'], ['spins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistical_suggestions_session_id'), 'statistical_suggestions', ['session_id'], unique=False)
    op.create_index(op.f('ix_statistical_suggestions_spin_id'), 'statistical_suggestions', ['spin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistical_suggestions_spin_id'), table_name='statistical_suggestions')
    op.drop_index(op.f('ix_statistical_suggestions_session_id'), table_name='statistical_suggestions')
    op.drop_table('statistical_suggestions')
    op.drop_index(op.f('ix_bets_spin_id'), table_name='bets')
    op.drop_index(op.f('ix_bets_session_id'), table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_bankroll_suggestions_spin_id'), table_name='bankroll_suggestions')
    op.drop_index(op.f('ix_bankroll_suggestions_session_id'), table_name='bankroll_suggestions')
    op.drop_table('bankroll_suggestions')
    op.drop_index(op.f('ix_spins_session_id'), table_name='spins')
    op.drop_table('spins')
    op.drop_table('session_performance')
    op.drop_index(op.f('ix_screenshot_uploads_user_id'), table_name='screenshot_uploads')
    op.drop_index(op.f('ix_screenshot_uploads_session_id'), table_name='screenshot_uploads')
    op.drop_index(op.f('ix_screenshot_uploads_image_hash'), table_name='screenshot_uploads')
    op.drop_table('screenshot_uploads')
    op.drop_index(op.f('ix_payment_events_subscription_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_game_variant_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_game_variants_game_id'), table_name='game_variants')
    op.drop_table('game_variants')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
